name: "[CI]"
on: [pull_request]

env: 
  TURBO_TELEMETRY_DISABLED: 1
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  lint:
    name: "💅 Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - name: "Use Node.Js"
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  format:
    name: "💅 Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2 

      - name: "Use Node.Js"
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Format
        run: pnpm format

  test:
    name: "🧪 Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - name: "Use Node.Js"
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test

  build-frontend:
    name: "📦 Build Frontend"
    runs-on: ubuntu-latest
    needs: [lint, format, test]
    steps:
      - uses: actions/checkout@v3

      - name: Create .env
        run: |
          echo ${{ secrets.frontend_env }} > .env.frontend
          echo ${{ secrets.backend_env }} > .env.backend

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          file: ./apps/frontend/Dockerfile
          context: .
          push: false

  build-backend:
    name: "📦 Build Backend"
    runs-on: ubuntu-latest
    needs: [lint, format, test]
    steps:
      - uses: actions/checkout@v3

      - name: Create .env
        run: |
          echo ${{ secrets.frontend_env }} > .env.frontend
          echo ${{ secrets.backend_env }} > .env.backend

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          file: ./apps/backend/Dockerfile
          context: .
          push: false